In [32]:
import pandas as pd

In [53]:
data = pd.read_csv("../../8-1.csv") # appro
data_2 = pd.read_csv("../../8-2.csv") # member
data_3 = pd.read_csv("../../8-3.csv") #
data_4 = pd.read_csv("../../8-4.csv") # appro

In [54]:
data

,발급회원번호,최종이용일자_일시불,최종이용일자_체크,최종이용일자_할부,이용개월수_일시불_R12M,이용개월수_할부_R12M,이용개월수_체크_R12M,이용금액_일시불_B0M,이용금액_체크_B0M,이용금액_할부_B0M,이용건수_일시불_B0M,이용건수_체크_B0M,이용건수_할부_B0M
0,SYN_2467848,20180816,20180831,20170709,12,5,12,692737,1145584,0,47,53,0
1,SYN_970249,20180831,20180701,20161129,12,0,3,954083,232026,0,44,0,0
2,SYN_2469653,20180831,10101,20141108,12,0,0,1470068,0,0,62,0,0
3,SYN_753729,20180823,10101,20170928,12,1,0,435910,0,0,45,0,0
4,SYN_860484,20180827,20180808,10101,12,1,8,2297678,462893,0,78,20,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,SYN_1966491,20180809,20180825,20180714,12,3,12,726260,428953,0,40,20,0
2999996,SYN_1128432,20180804,10101,20180616,12,2,0,143691,0,0,40,0,0
2999997,SYN_492747,20180807,20180215,20180819,12,9,3,601343,0,610461,40,0,2
2999998,SYN_188884,20180806,10101,20180626,12,4,0,1003897,0,0,40,0,0
2999999,SYN_2355455,20180816,20180818,20180427,12,3,9,999568,431921,0,40,17,0

In [55]:
data_2

,발급회원번호,남녀구분코드,연령,VIP등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,입회경과개월수_신용,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,마케팅동의여부,이용금액_R3M_신용
0,SYN_2518672,1,30대,_,0,0,0,74,0,0,0,0,0
1,SYN_1509599,1,30대,_,0,0,0,66,0,0,0,1,0
2,SYN_1513112,2,50대,_,0,0,0,241,0,0,0,0,0
3,SYN_1516329,1,30대,_,0,0,0,85,1,105,0,1,0
4,SYN_1523933,1,30대,_,0,0,0,83,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,SYN_1426911,2,40대,06,1,1,0,183,1,46,0,0,9208194
2999996,SYN_490126,1,40대,07,1,0,0,76,0,0,0,0,7108006
2999997,SYN_498094,2,30대,06,1,1,1,55,1,100,0,0,10865695
2999998,SYN_154670,1,40대,07,1,1,1,144,1,103,0,1,12605899
2999999,SYN_1829463,1,30대,06,1,1,1,86,0,0,0,1,11581024

In [56]:
data_3

              발급회원번호  유효카드수_신용체크  유효카드수_신용  유효카드수_체크
0        SYN_2510861           2         2         0
1        SYN_2514103           1         1         0
2        SYN_2521009           1         1         0
3        SYN_2521290           1         1         0
4        SYN_2534733           0         0         0
...              ...         ...       ...       ...
2999995   SYN_443735           7         5         2
2999996   SYN_449189           7         5         2
2999997  SYN_1497713           7         4         3
2999998  SYN_1243738           8         5         3
2999999  SYN_1404185           8         5         3

[3000000 rows x 4 columns]

In [57]:
data_4

,발급회원번호,최대이용금액_일시불_R12M,최대이용금액_할부_R12M,최대이용금액_체크_R12M,이용금액_업종기준,이용후경과월_일시불,이용후경과월_체크,이용후경과월_할부
0,SYN_2599110,1422592,400118,0,852879,0,12,10
1,SYN_1678927,1118593,229740,0,179528,0,12,10
2,SYN_1175610,1066176,274220,0,1228850,0,12,10
3,SYN_2273417,1563551,363444,0,2264802,0,12,10
4,SYN_792784,1575793,658524,0,1715725,0,12,10
...,...,...,...,...,...,...,...,...
2999995,SYN_425633,34347,0,0,0,0,12,12
2999996,SYN_91318,92821,0,0,138936,12,12,12
2999997,SYN_961792,0,0,0,0,12,12,12
2999998,SYN_962008,1708743,0,344920,257758,0,0,12
2999999,SYN_1707518,723815,0,0,2279385,0,12,12

In [58]:
merged_df = pd.merge(data,data_2,on='발급회원번호',how='inner')

In [59]:
merged_df2 = pd.merge(merged_df,data_3, on='발급회원번호',how='inner')

In [60]:
last = pd.merge(merged_df2, data_4, on='발급회원번호', how = 'inner')

In [66]:
def preprocess_feature(data):
    data['VIP등급코드'] = data['VIP등급코드'].str.replace("_","0").astype(int)
    
    data['연령'] = data['연령'].str.replace('대|이상','',regex=True).astype(int)
    # 이용건수 합치기 예시
    data['이용건수_B0M'] = data[['이용건수_일시불_B0M', '이용건수_체크_B0M', '이용건수_할부_B0M']].sum(axis=1)

    # 이용금액 합치기 예시
    data['이용금액_B0M'] = data[['이용금액_일시불_B0M', '이용금액_체크_B0M', '이용금액_할부_B0M']].sum(axis=1)

    # 이용개월수 합치기 예시
    data['이용개월수_R12M'] = data[['이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_체크_R12M']].sum(axis=1)

    # 유효카드수 합치기 예시
    data['유효카드수_총합'] = data[['유효카드수_신용체크', '유효카드수_신용', '유효카드수_체크']].sum(axis=1)

    # 최종 이용일자 최신값 선택 (datetime이라 .max()가 정확히 동작함)
    data['최종이용일자_종합'] = data[['최종이용일자_일시불', '최종이용일자_체크', '최종이용일자_할부']].max(axis=1)

    # 필요 없는 원본 컬럼 제거 (존재하는 컬럼만)
    cols_to_drop = [
        '이용건수_일시불_B0M', '이용건수_체크_B0M', '이용건수_할부_B0M',
        '이용금액_일시불_B0M', '이용금액_체크_B0M', '이용금액_할부_B0M',
        '이용개월수_일시불_R12M', '이용개월수_할부_R12M', '이용개월수_체크_R12M',
        '유효카드수_신용체크', '유효카드수_신용', '유효카드수_체크',
        '최종이용일자_일시불', '최종이용일자_체크', '최종이용일자_할부','발급회원번호'
    ]
    drop_cols = [col for col in cols_to_drop if col in data.columns]
    data.drop(columns=drop_cols, inplace=True)

    return data

In [63]:
preprocess_feature(last)

,발급회원번호,남녀구분코드,연령,VIP등급코드,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,입회경과개월수_신용,탈회횟수_누적,최종탈회후경과월,...,최대이용금액_체크_R12M,이용금액_업종기준,이용후경과월_일시불,이용후경과월_체크,이용후경과월_할부,이용건수_B0M,이용금액_B0M,이용개월수_R12M,유효카드수_총합,최종이용일자_종합
0,SYN_2467848,2,20,7,1,0,0,13,0,0,...,3375912,5589197,0,0,2,100,1838321,29,2,20180831
1,SYN_970249,1,40,0,1,1,0,56,1,102,...,102066,1974381,0,1,12,44,1186109,15,6,20180831
2,SYN_2469653,1,40,7,1,1,1,95,0,0,...,0,3184953,0,12,12,62,1470068,12,4,20180831
3,SYN_753729,2,30,0,1,1,1,78,0,0,...,0,970195,0,12,8,45,435910,13,2,20180823
4,SYN_860484,1,30,6,1,1,1,112,1,45,...,949616,6980477,0,0,12,98,2760571,21,6,20180827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,SYN_1966491,2,40,7,1,1,0,62,0,0,...,716046,2847258,0,0,4,60,1155213,27,6,20180825
2999996,SYN_1128432,2,40,0,1,1,1,244,0,0,...,0,869561,0,12,2,40,143691,14,2,20180804
2999997,SYN_492747,2,20,7,1,1,0,29,0,0,...,115041,7056961,0,6,0,42,1211804,24,8,20180819
2999998,SYN_188884,2,50,7,1,0,1,151,0,0,...,0,2902099,0,12,2,40,1003897,16,8,20180806
2999999,SYN_2355455,1,30,7,1,1,0,29,1,46,...,761444,3645489,0,0,5,57,1431489,24,6,20180818

In [ ]:
# last.to_csv("8_data_index.csv",index=False) #발급회원번호가 포함된 csv파일일

In [43]:
model_data = pd.read_csv("../../model_data.csv")

In [45]:
set(last) - set(model_data)

set()

In [46]:
set(model_data) - set(last)

{'Unnamed: 0', '청구금액_B0'}

In [47]:
model_data = model_data.drop(columns=['Unnamed: 0','청구금액_B0'])

In [48]:
last = last[model_data.columns]

In [49]:
last

,VIP등급코드,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,입회경과개월수_신용,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,...,이용후경과월_체크,최대이용금액_일시불_R12M,최대이용금액_할부_R12M,최대이용금액_체크_R12M,이용금액_업종기준,이용건수_B0M,이용금액_B0M,이용개월수_R12M,유효카드수_총합,최종이용일자_종합
0,7,2,20,1,0,0,13,0,0,0,...,0,2109234,1748317,3375912,5589197,100,1838321,29,2,20180831
1,0,1,40,1,1,0,56,1,102,0,...,1,1403023,0,102066,1974381,44,1186109,15,6,20180831
2,7,1,40,1,1,1,95,0,0,0,...,12,3690016,0,0,3184953,62,1470068,12,4,20180831
3,0,2,30,1,1,1,78,0,0,0,...,12,872865,106942,0,970195,45,435910,13,2,20180823
4,6,1,30,1,1,1,112,1,45,0,...,0,3797897,0,949616,6980477,98,2760571,21,6,20180827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,7,2,40,1,1,0,62,0,0,0,...,0,2023521,1838173,716046,2847258,60,1155213,27,6,20180825
2999996,0,2,40,1,1,1,244,0,0,0,...,12,269351,218437,0,869561,40,143691,14,2,20180804
2999997,7,2,20,1,1,0,29,0,0,0,...,6,1176178,2451548,115041,7056961,42,1211804,24,8,20180819
2999998,7,2,50,1,0,1,151,0,0,0,...,12,1964008,528883,0,2902099,40,1003897,16,8,20180806
2999999,7,1,30,1,1,0,29,1,46,0,...,0,1464904,841168,761444,3645489,57,1431489,24,6,20180818

In [50]:
model_data

,VIP등급코드,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,입회경과개월수_신용,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,...,이용후경과월_체크,최대이용금액_일시불_R12M,최대이용금액_할부_R12M,최대이용금액_체크_R12M,이용금액_업종기준,이용건수_B0M,이용금액_B0M,이용개월수_R12M,유효카드수_총합,최종이용일자_종합
0,0,2,40,0,0,0,166,0,0,0,...,12,0,0,0,0,1,0,0,2,20180716
1,0,1,30,0,0,0,103,0,0,0,...,12,19070,0,0,0,-1,0,2,4,20170917
2,0,2,60,0,0,0,8,0,0,0,...,12,301285,0,0,0,0,0,4,0,20180102
3,0,2,30,0,0,0,2,2,18,0,...,12,0,0,0,0,-1,0,0,2,10101
4,0,1,40,0,0,0,72,0,0,0,...,12,0,0,0,0,0,0,0,2,20160408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,6,1,40,1,1,0,262,1,45,0,...,7,2521359,980459,157548,6937435,82,2129608,19,14,20180730
2999996,6,1,50,1,1,1,272,0,0,0,...,1,3659484,0,196841,4944998,47,1605615,16,14,20180728
2999997,7,1,30,1,1,1,86,1,96,0,...,12,4028389,0,0,4011335,53,1163258,12,16,20180705
2999998,7,1,40,1,1,1,136,1,100,0,...,12,6073370,421386,0,8598625,69,2413165,13,16,20180731
2999999,0,2,30,1,1,0,109,0,0,0,...,10,3885829,3290800,104363,26220132,72,2766192,24,16,20180731

In [51]:
last

,VIP등급코드,남녀구분코드,연령,회원여부_이용가능,회원여부_이용가능_CA,회원여부_이용가능_카드론,입회경과개월수_신용,탈회횟수_누적,최종탈회후경과월,탈회횟수_발급6개월이내,...,이용후경과월_체크,최대이용금액_일시불_R12M,최대이용금액_할부_R12M,최대이용금액_체크_R12M,이용금액_업종기준,이용건수_B0M,이용금액_B0M,이용개월수_R12M,유효카드수_총합,최종이용일자_종합
0,7,2,20,1,0,0,13,0,0,0,...,0,2109234,1748317,3375912,5589197,100,1838321,29,2,20180831
1,0,1,40,1,1,0,56,1,102,0,...,1,1403023,0,102066,1974381,44,1186109,15,6,20180831
2,7,1,40,1,1,1,95,0,0,0,...,12,3690016,0,0,3184953,62,1470068,12,4,20180831
3,0,2,30,1,1,1,78,0,0,0,...,12,872865,106942,0,970195,45,435910,13,2,20180823
4,6,1,30,1,1,1,112,1,45,0,...,0,3797897,0,949616,6980477,98,2760571,21,6,20180827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999995,7,2,40,1,1,0,62,0,0,0,...,0,2023521,1838173,716046,2847258,60,1155213,27,6,20180825
2999996,0,2,40,1,1,1,244,0,0,0,...,12,269351,218437,0,869561,40,143691,14,2,20180804
2999997,7,2,20,1,1,0,29,0,0,0,...,6,1176178,2451548,115041,7056961,42,1211804,24,8,20180819
2999998,7,2,50,1,0,1,151,0,0,0,...,12,1964008,528883,0,2902099,40,1003897,16,8,20180806
2999999,7,1,30,1,1,0,29,1,46,0,...,0,1464904,841168,761444,3645489,57,1431489,24,6,20180818

In [ ]:
# last.to_csv('8_data.csv',index=False) # 발급회원번호가 제외된 csv 파일